# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 14) do

  create_table "comments", :force => true do |t|
    t.column "user_id",    :integer,  :default => 0,  :null => false
    t.column "memory_id",  :integer,  :default => 0,  :null => false
    t.column "parent_id",  :integer
    t.column "title",      :string,   :default => "", :null => false
    t.column "body",       :text,     :default => "", :null => false
    t.column "updated_on", :datetime
    t.column "created_on", :datetime
  end

  add_index "comments", ["user_id"], :name => "index_comments_on_user_id"
  add_index "comments", ["memory_id"], :name => "index_comments_on_memory_id"

  create_table "friends_memories", :id => false, :force => true do |t|
    t.column "friend_id", :integer, :default => 0, :null => false
    t.column "memory_id", :integer, :default => 0, :null => false
  end

  add_index "friends_memories", ["friend_id"], :name => "index_friends_memories_on_friend_id"
  add_index "friends_memories", ["memory_id"], :name => "index_friends_memories_on_memory_id"

  create_table "friends_users", :id => false, :force => true do |t|
    t.column "friend_id", :integer, :default => 0, :null => false
    t.column "user_id",   :integer, :default => 0, :null => false
  end

  add_index "friends_users", ["friend_id"], :name => "index_friends_users_on_friend_id"
  add_index "friends_users", ["user_id"], :name => "index_friends_users_on_user_id"

  create_table "memories", :force => true do |t|
    t.column "title",      :string,   :default => "", :null => false
    t.column "body",       :text,     :default => "", :null => false
    t.column "user_id",    :integer,  :default => 0,  :null => false
    t.column "url_name",   :string,   :default => "", :null => false
    t.column "year",       :integer,  :default => 0,  :null => false
    t.column "month",      :integer
    t.column "day",        :integer
    t.column "updated_on", :datetime
    t.column "created_on", :datetime
  end

  add_index "memories", ["year"], :name => "index_memories_on_year"
  add_index "memories", ["month"], :name => "index_memories_on_month"
  add_index "memories", ["day"], :name => "index_memories_on_day"
  add_index "memories", ["url_name"], :name => "index_memories_on_url_name"

  create_table "memories_tags", :id => false, :force => true do |t|
    t.column "tag_id",    :integer, :default => 0, :null => false
    t.column "memory_id", :integer, :default => 0, :null => false
  end

  add_index "memories_tags", ["tag_id"], :name => "index_memories_tags_on_tag_id"
  add_index "memories_tags", ["memory_id"], :name => "index_memories_tags_on_memory_id"

  create_table "photos", :force => true do |t|
    t.column "memory_id",    :integer
    t.column "user_id",      :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
  end

  add_index "photos", ["memory_id"], :name => "index_photos_on_memory_id"
  add_index "photos", ["user_id"], :name => "index_photos_on_user_id"

  create_table "recovery_sessions", :force => true do |t|
    t.column "user_id",     :integer,                :default => 0,  :null => false
    t.column "remember_me", :string,   :limit => 32, :default => "", :null => false
    t.column "created_on",  :datetime
    t.column "updated_on",  :datetime
  end

  add_index "recovery_sessions", ["remember_me"], :name => "index_recovery_sessions_on_remember_me"

  create_table "tags", :force => true do |t|
    t.column "name",     :string, :default => "", :null => false
    t.column "url_name", :string, :default => "", :null => false
    t.column "category", :string
  end

  add_index "tags", ["url_name"], :name => "index_tags_on_url_name"

  create_table "users", :force => true do |t|
    t.column "nickname",        :string,   :limit => 100, :default => "", :null => false
    t.column "forename",        :string
    t.column "surname",         :string
    t.column "email",           :string,                  :default => "", :null => false
    t.column "password",        :string,   :limit => 32,  :default => "", :null => false
    t.column "date_of_birth",   :date
    t.column "gender",          :string,   :limit => 1
    t.column "description",     :text
    t.column "subscribe",       :boolean
    t.column "activation_code", :string
    t.column "activation_date", :datetime
    t.column "admin",           :integer
    t.column "updated_on",      :datetime
    t.column "created_on",      :datetime
  end

  add_index "users", ["activation_code"], :name => "index_users_on_activation_code"
  add_index "users", ["nickname"], :name => "index_users_on_nickname"
  add_index "users", ["email"], :name => "index_users_on_email"

end
